import 'reflect-metadata';
import { DataSource } from 'typeorm';
import { Job, JobType, JobStatus, ExperienceLevel, WorkFormat } from '../jobs/entities/job.entity';
import { User } from '../users/entities/user.entity';
import { Company, CompanyStatus, CompanySize } from '../companies/entities/company.entity';
import { Application, ApplicationStatus } from '../applications/entities/application.entity';
import { Skill } from '../skills/entities/skill.entity';
import { SkillCategory } from '../skills/entities/skill-category.entity';
import { SavedJob } from '../jobs/entities/saved-job.entity';
import { CompanyReview } from '../companies/entities/company-review.entity';
import { Notification } from '../notifications/entities/notification.entity';
import { RefreshToken } from '../auth/entities/refresh-token.entity';
import { AuditLog } from '../admin/entities/audit-log.entity';
import { Message } from '../chat/entities/message.entity';

const DB = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT) || 5432,
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || 'Strong_New_Password_123!',
  database: process.env.DB_DATABASE || 'youth_job_platform',
  entities: [
    User, Company, CompanyReview, Job, SavedJob, Application,
    Skill, SkillCategory, Notification, RefreshToken, AuditLog, Message,
  ],
  synchronize: false,
});

async function main() {
  await DB.initialize();
  console.log('✅ DB connected');

  await DB.query('DELETE FROM applications');
  await DB.query('DELETE FROM saved_jobs');
  await DB.query('DELETE FROM job_skills');
  await DB.query('DELETE FROM jobs');
  console.log('🗑️  Cleared old jobs');

  const userRepo = DB.getRepository(User);
  const jobRepo  = DB.getRepository(Job);
  const skillRepo = DB.getRepository(Skill);

  const employers = await userRepo.find({ where: [
    { email: 'employer@itsolutions.ua' },
    { email: 'employer@startuphub.ua' },
    { email: 'employer@globaldev.ua' },
  ]});

  if (employers.length === 0) {
    console.error('❌ No employers found. Run the main seed first.');
    process.exit(1);
  }

  const emp = (i: number) => employers[i % employers.length];

  const allSkills = await skillRepo.find();
  const skill = (name: string) => allSkills.find(s => s.name === name);
  const skills = (...names: string[]): Skill[] =>
    names.map(n => skill(n)).filter(Boolean) as Skill[];

  type JobDef = {
    title: string; description: string; requirements: string;
    responsibilities: string; benefits: string;
    jobType: JobType; experienceLevel: ExperienceLevel;
    workFormat: WorkFormat; country: string; city: string;
    salaryMin?: number; salaryMax?: number; salaryCurrency?: string;
    isSalaryNegotiable?: boolean; category: string;
    skillNames: string[]; employerIdx: number;
    vacanciesCount?: number; requiredLanguages?: string[];
    tags?: string[];
  };

  const JOBS: JobDef[] = [
    // ── IT (11) ──────────────────────────────────────────────────────────────
    {
      title: 'Frontend Developer (React)',
      description: 'We are looking for a passionate Frontend Developer to join our remote-first product team. You will build high-performance web interfaces used by thousands of users daily.',
      requirements: '1+ year of commercial React.js experience. Strong knowledge of HTML/CSS. Understanding of REST APIs.',
      responsibilities: 'Develop and maintain UI components. Collaborate with designers. Write unit tests. Participate in code reviews.',
      benefits: 'Fully remote work. Flexible hours. Health insurance. Learning budget €500/year.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.REMOTE, country: 'Poland', city: 'Warsaw',
      salaryMin: 4000, salaryMax: 6000, salaryCurrency: 'PLN',
      category: 'it', skillNames: ['React.js', 'TypeScript', 'HTML/CSS', 'Git'],
      employerIdx: 0, vacanciesCount: 2, requiredLanguages: ['English'],
      tags: ['react', 'frontend', 'remote'],
    },
    {
      title: 'Backend Engineer (Node.js)',
      description: 'Join our growing engineering team in Berlin to build scalable microservices powering a leading European fintech platform.',
      requirements: '3+ years with Node.js. Experience with PostgreSQL and Redis. Knowledge of REST API design.',
      responsibilities: 'Design and implement backend services. Optimize database queries. Ensure security best practices. Write integration tests.',
      benefits: 'Hybrid work. 30 days vacation. Relocation support. Stock options.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Germany', city: 'Berlin',
      salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'EUR',
      category: 'it', skillNames: ['Node.js', 'NestJS', 'PostgreSQL', 'Redis', 'Docker'],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English', 'German'],
      tags: ['nodejs', 'backend', 'fintech'],
    },
    {
      title: 'DevOps Engineer',
      description: 'We are hiring a DevOps Engineer to own our cloud infrastructure and CI/CD pipelines. You will work on a platform serving millions of requests per day.',
      requirements: '4+ years in DevOps/SRE. Expertise in Kubernetes and AWS. Strong Linux skills. Experience with Terraform.',
      responsibilities: 'Manage and scale Kubernetes clusters. Build CI/CD pipelines. Monitor infrastructure. Incident response.',
      benefits: 'Fully remote. Competitive salary. RSUs. Annual retreat.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.REMOTE, country: 'USA', city: 'San Francisco',
      salaryMin: 130000, salaryMax: 170000, salaryCurrency: 'USD',
      category: 'it', skillNames: ['Kubernetes', 'AWS', 'Docker', 'CI/CD', 'Linux', 'Terraform'],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['devops', 'aws', 'kubernetes'],
    },
    {
      title: 'Mobile Developer (Flutter)',
      description: 'Join a Kyiv-based startup building a cross-platform mobile app for gig workers. You will be the primary mobile engineer on the team.',
      requirements: '1+ year Flutter experience. Dart proficiency. Familiarity with REST APIs. Understanding of state management (BLoC/Riverpod).',
      responsibilities: 'Build and maintain Flutter app. Collaborate with backend team. Release to App Store and Google Play. Write tests.',
      benefits: 'Remote work. Flexible hours. Equity participation. Gym compensation.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.REMOTE, country: 'Ukraine', city: 'Kyiv',
      salaryMin: 45000, salaryMax: 65000, salaryCurrency: 'UAH',
      category: 'it', skillNames: ['Flutter', 'Dart', 'Git', 'REST API'],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['Ukrainian', 'English'],
      tags: ['flutter', 'mobile', 'startup'],
    },
    {
      title: 'Full Stack Developer',
      description: 'Growing London agency seeks a Full Stack Developer to deliver web applications for enterprise clients across finance and retail.',
      requirements: '3+ years full-stack experience. React.js and Node.js proficiency. Experience with PostgreSQL. Good communication skills.',
      responsibilities: 'Develop end-to-end features. Participate in client calls. Conduct code reviews. Mentor junior developers.',
      benefits: 'Hybrid 3 days/week. 25 days holiday. Private health insurance. Season ticket loan.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'United Kingdom', city: 'London',
      salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP',
      category: 'it', skillNames: ['React.js', 'Node.js', 'PostgreSQL', 'TypeScript'],
      employerIdx: 1, vacanciesCount: 2, requiredLanguages: ['English'],
      tags: ['fullstack', 'react', 'nodejs'],
    },
    {
      title: 'Data Engineer',
      description: 'A leading Dutch e-commerce company is looking for a Data Engineer to build and maintain data pipelines that power our analytics and ML teams.',
      requirements: '4+ years in data engineering. Python expertise. SQL mastery. Experience with Spark or Airflow.',
      responsibilities: 'Design and build ETL pipelines. Maintain data warehouse. Collaborate with data scientists. Ensure data quality.',
      benefits: 'Hybrid work in Amsterdam. 26 vacation days. NS travel card. Annual bonus.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'Netherlands', city: 'Amsterdam',
      salaryMin: 75000, salaryMax: 95000, salaryCurrency: 'EUR',
      category: 'it', skillNames: ['Python', 'SQL', 'PostgreSQL', 'Docker'],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['data-engineering', 'python', 'sql'],
    },
    {
      title: 'Machine Learning Engineer',
      description: 'Toronto AI startup is hiring an ML Engineer to build and productionize machine learning models for real-time fraud detection.',
      requirements: '3+ years in ML/AI. Python and TensorFlow/PyTorch proficiency. Experience deploying models to production.',
      responsibilities: 'Build ML models. Create training pipelines. Monitor model performance. Collaborate with data scientists.',
      benefits: 'Remote-first. Stock options. Flexible hours. Conference budget.',
      jobType: JobType.CONTRACT, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.REMOTE, country: 'Canada', city: 'Toronto',
      salaryMin: 110000, salaryMax: 140000, salaryCurrency: 'CAD',
      category: 'it', skillNames: ['Python', 'Machine Learning', 'TensorFlow', 'SQL'],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['machine-learning', 'ai', 'python'],
    },
    {
      title: 'QA Automation Engineer',
      description: 'Tel Aviv SaaS company seeks a QA Automation Engineer to build test frameworks ensuring quality across web and mobile platforms.',
      requirements: '3+ years QA automation. JavaScript or Python test frameworks. Experience with Selenium/Playwright. API testing.',
      responsibilities: 'Develop automated test suites. Integrate tests into CI/CD. Analyze test failures. Maintain test infrastructure.',
      benefits: 'Hybrid work. 23 vacation days. Meal allowance. Stock options.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Israel', city: 'Tel Aviv',
      salaryMin: 35000, salaryMax: 50000, salaryCurrency: 'ILS',
      category: 'it', skillNames: ['JavaScript', 'Python', 'CI/CD', 'Git'],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English', 'Hebrew'],
      tags: ['qa', 'automation', 'testing'],
    },
    {
      title: 'Cybersecurity Analyst',
      description: 'Vienna-based banking institution seeks a Cybersecurity Analyst to protect critical infrastructure and respond to security incidents.',
      requirements: '5+ years in cybersecurity. CISSP or CEH certification preferred. Experience with SIEM tools. Knowledge of ISO 27001.',
      responsibilities: 'Monitor security events. Conduct vulnerability assessments. Respond to incidents. Develop security policies.',
      benefits: 'Office work. Excellent pension scheme. 30 days vacation. Training budget.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.OFFICE, country: 'Austria', city: 'Vienna',
      salaryMin: 70000, salaryMax: 90000, salaryCurrency: 'EUR',
      category: 'it', skillNames: ['Linux', 'SQL', 'Python'],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'German'],
      tags: ['cybersecurity', 'infosec', 'banking'],
    },
    {
      title: 'React Developer (Internship)',
      description: 'Prague product company offers a paid internship for aspiring React developers. Work on real features alongside experienced mentors.',
      requirements: 'Basic HTML/CSS/JavaScript knowledge. Familiarity with React. Strong motivation to learn. English B1+.',
      responsibilities: 'Implement UI components under supervision. Fix bugs. Write documentation. Participate in sprint ceremonies.',
      benefits: 'Paid internship. Mentorship program. Possibility of full-time hire. Central Prague office.',
      jobType: JobType.INTERNSHIP, experienceLevel: ExperienceLevel.INTERN,
      workFormat: WorkFormat.HYBRID, country: 'Czech Republic', city: 'Prague',
      salaryMin: 20000, salaryMax: 30000, salaryCurrency: 'CZK',
      category: 'it', skillNames: ['React.js', 'HTML/CSS', 'JavaScript'],
      employerIdx: 0, vacanciesCount: 3, requiredLanguages: ['English'],
      tags: ['internship', 'react', 'junior'],
    },
    {
      title: 'Cloud Architect',
      description: 'Dubai tech consultancy is looking for a Cloud Architect to lead enterprise cloud transformation projects for clients in the GCC region.',
      requirements: '8+ years in IT. 5+ years cloud architecture. AWS or Azure certifications. Strong stakeholder communication.',
      responsibilities: 'Design cloud solutions. Lead technical proposals. Oversee cloud migrations. Mentor engineering teams.',
      benefits: 'Tax-free salary. Housing allowance. Flight tickets. Health insurance for family.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.LEAD,
      workFormat: WorkFormat.OFFICE, country: 'UAE', city: 'Dubai',
      salaryMin: 25000, salaryMax: 35000, salaryCurrency: 'AED',
      category: 'it', skillNames: ['AWS', 'Docker', 'Kubernetes', 'Linux'],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English', 'Arabic'],
      tags: ['cloud', 'aws', 'architecture'],
    },

    // ── Design (4) ───────────────────────────────────────────────────────────
    {
      title: 'UI/UX Designer',
      description: 'Lviv-based product studio is looking for a UI/UX Designer to shape user experiences for web and mobile products across EdTech and HealthTech sectors.',
      requirements: '2+ years UI/UX design experience. Figma proficiency. Portfolio required. User research skills.',
      responsibilities: 'Conduct user research. Create wireframes and prototypes. Collaborate with developers. Conduct usability tests.',
      benefits: 'Fully remote. Flexible schedule. Design conference budget. Equipment allowance.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.REMOTE, country: 'Ukraine', city: 'Lviv',
      salaryMin: 50000, salaryMax: 80000, salaryCurrency: 'UAH',
      category: 'design', skillNames: ['Figma', 'UI/UX Design', 'Adobe XD'],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['Ukrainian', 'English'],
      tags: ['ux', 'ui', 'figma'],
    },
    {
      title: 'Graphic Designer',
      description: 'Paris marketing agency seeks a creative Graphic Designer to produce visual materials for international brand campaigns.',
      requirements: '1+ year design experience. Adobe Creative Suite proficiency. Strong portfolio. Eye for typography.',
      responsibilities: 'Create print and digital assets. Work on brand guidelines. Collaborate with copywriters. Prepare files for production.',
      benefits: 'Office in central Paris. 25 days holiday. Metro pass. Team lunches.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.OFFICE, country: 'France', city: 'Paris',
      salaryMin: 28000, salaryMax: 36000, salaryCurrency: 'EUR',
      category: 'design', skillNames: ['Photoshop', 'Illustrator', 'Figma'],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['French', 'English'],
      tags: ['graphic-design', 'branding', 'creative'],
    },
    {
      title: 'Motion Designer',
      description: 'Barcelona-based digital agency seeks a freelance Motion Designer for a 6-month project creating animated content for social media campaigns.',
      requirements: '3+ years motion design experience. After Effects and Premiere proficiency. Experience with social media formats.',
      responsibilities: 'Create animated videos and GIFs. Develop motion graphics. Work with art directors. Deliver assets on time.',
      benefits: 'Flexible freelance schedule. Remote work. Competitive day rate.',
      jobType: JobType.FREELANCE, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.REMOTE, country: 'Spain', city: 'Barcelona',
      salaryMin: 400, salaryMax: 600, salaryCurrency: 'EUR',
      category: 'design', skillNames: ['Figma', 'Photoshop', 'Illustrator'],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English', 'Spanish'],
      tags: ['motion', 'animation', 'freelance'],
    },
    {
      title: 'Brand Designer',
      description: 'Stockholm startup is growing their design team and seeks a talented Brand Designer to define and evolve our visual identity across all touchpoints.',
      requirements: '4+ years brand design experience. Portfolio with brand projects. Figma and Illustrator skills. Strategic thinking.',
      responsibilities: 'Develop brand identity systems. Create design guidelines. Produce marketing materials. Collaborate with marketing and product teams.',
      benefits: 'Hybrid work. 6 weeks vacation. Parental leave top-up. Wellness budget.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'Sweden', city: 'Stockholm',
      salaryMin: 55000, salaryMax: 72000, salaryCurrency: 'SEK',
      category: 'design', skillNames: ['Figma', 'Illustrator', 'Photoshop', 'Sketch'],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'Swedish'],
      tags: ['brand', 'identity', 'design'],
    },

    // ── Marketing (5) ────────────────────────────────────────────────────────
    {
      title: 'Digital Marketing Manager',
      description: 'Warsaw-based e-commerce company seeks a Digital Marketing Manager to drive acquisition across paid channels for the CEE market.',
      requirements: '3+ years digital marketing. Google Ads and Meta Ads experience. Analytics proficiency. Data-driven mindset.',
      responsibilities: 'Manage paid ad campaigns. Analyze and optimize performance. Collaborate with creative team. Report to CMO.',
      benefits: 'Hybrid work. Performance bonus. Training budget. Private healthcare.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Poland', city: 'Warsaw',
      salaryMin: 10000, salaryMax: 15000, salaryCurrency: 'PLN',
      category: 'marketing', skillNames: ['SQL'],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['Polish', 'English'],
      tags: ['digital-marketing', 'paid-ads', 'ecommerce'],
    },
    {
      title: 'SEO Specialist',
      description: 'New York content agency is hiring a remote SEO Specialist to grow organic traffic for SaaS and B2B clients.',
      requirements: '2+ years SEO experience. Proficiency in Ahrefs/SEMrush. Technical SEO knowledge. Content strategy skills.',
      responsibilities: 'Conduct keyword research. Optimize on-page and technical SEO. Build content calendars. Report on rankings.',
      benefits: 'Fully remote. Flexible hours. Health insurance stipend. Home office budget.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.REMOTE, country: 'USA', city: 'New York',
      salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'USD',
      category: 'marketing', skillNames: [],
      employerIdx: 1, vacanciesCount: 2, requiredLanguages: ['English'],
      tags: ['seo', 'content', 'remote'],
    },
    {
      title: 'Content Marketing Manager',
      description: 'Munich B2B SaaS company seeks a Content Marketing Manager to build a thought leadership program and drive demand generation through content.',
      requirements: '4+ years content marketing in B2B. Excellent English writing. Experience with HubSpot. Data analysis skills.',
      responsibilities: 'Create content strategy. Produce blog posts and whitepapers. Manage external writers. Measure content ROI.',
      benefits: 'Hybrid 2 days/week. 28 days vacation. DB job ticket. Company events.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'Germany', city: 'Munich',
      salaryMin: 65000, salaryMax: 80000, salaryCurrency: 'EUR',
      category: 'marketing', skillNames: [],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'German'],
      tags: ['content', 'b2b', 'saas'],
    },
    {
      title: 'Social Media Manager',
      description: 'Kyiv lifestyle brand is looking for a creative Social Media Manager to grow our presence on Instagram, TikTok, and YouTube.',
      requirements: '1+ year social media management. Instagram and TikTok content creation. Basic video editing. Analytical mindset.',
      responsibilities: 'Create and schedule content. Manage community. Run collaborations with influencers. Report on KPIs.',
      benefits: 'Remote work. Flexible hours. Product discounts. Creative freedom.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.REMOTE, country: 'Ukraine', city: 'Kyiv',
      salaryMin: 25000, salaryMax: 40000, salaryCurrency: 'UAH',
      category: 'marketing', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['Ukrainian'],
      tags: ['social-media', 'instagram', 'tiktok'],
    },
    {
      title: 'Performance Marketing Specialist',
      description: 'Sydney-based DTC brand is looking for a Performance Marketing Specialist (contract) to scale their Meta and Google advertising.',
      requirements: '3+ years performance marketing. ROAS optimization experience. Shopify familiarity. Strong analytical skills.',
      responsibilities: 'Plan and execute paid campaigns. A/B test creatives. Optimize ad spend. Coordinate with creative team.',
      benefits: 'Remote-first. Flexible contract terms. Competitive day rate. Potential to go full-time.',
      jobType: JobType.CONTRACT, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.REMOTE, country: 'Australia', city: 'Sydney',
      salaryMin: 90000, salaryMax: 110000, salaryCurrency: 'AUD',
      category: 'marketing', skillNames: [],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['performance-marketing', 'dtc', 'ads'],
    },

    // ── Finance (4) ──────────────────────────────────────────────────────────
    {
      title: 'Financial Analyst',
      description: 'Zurich private equity firm seeks a Financial Analyst to support investment decisions through financial modelling and due diligence.',
      requirements: '2+ years financial analysis. CFA progress preferred. Excel and PowerPoint proficiency. Strong analytical skills.',
      responsibilities: 'Build financial models. Conduct industry research. Prepare investment memos. Support portfolio monitoring.',
      benefits: 'Office in Zurich city centre. Bonus scheme. Lunch allowance. Excellent career growth.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.OFFICE, country: 'Switzerland', city: 'Zurich',
      salaryMin: 95000, salaryMax: 120000, salaryCurrency: 'CHF',
      category: 'finance', skillNames: ['SQL'],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'German'],
      tags: ['finance', 'private-equity', 'analysis'],
    },
    {
      title: 'Investment Analyst',
      description: 'London hedge fund is looking for a junior Investment Analyst to support portfolio managers in equity research and trading.',
      requirements: 'Strong academic background in finance or economics. Bloomberg proficiency. Python/VBA for data analysis preferred.',
      responsibilities: 'Research equities and sectors. Maintain financial models. Prepare research reports. Monitor market developments.',
      benefits: 'Competitive base + bonus. Private healthcare. 25 days leave. Pension.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.OFFICE, country: 'United Kingdom', city: 'London',
      salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'GBP',
      category: 'finance', skillNames: ['Python', 'SQL'],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['investment', 'hedge-fund', 'equity'],
    },
    {
      title: 'Risk Analyst',
      description: 'Frankfurt international bank seeks a Risk Analyst to identify, assess, and mitigate credit and market risks in the trading book.',
      requirements: '3+ years risk management experience. Knowledge of Basel III. SQL proficiency. FRM or equivalent preferred.',
      responsibilities: 'Monitor risk metrics. Prepare risk reports. Develop risk models. Collaborate with trading desks.',
      benefits: 'Hybrid work. Competitive salary. Banking benefits. Corporate language courses.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Germany', city: 'Frankfurt',
      salaryMin: 70000, salaryMax: 90000, salaryCurrency: 'EUR',
      category: 'finance', skillNames: ['SQL', 'Python'],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English', 'German'],
      tags: ['risk', 'banking', 'quantitative'],
    },
    {
      title: 'CFO',
      description: 'Fast-growing Singapore fintech startup is looking for a Chief Financial Officer to lead all financial operations and investor relations.',
      requirements: '10+ years finance experience. 3+ years CFO or VP Finance. CPA/CFA required. Experience with startup fundraising.',
      responsibilities: 'Own P&L and financial reporting. Lead fundraising rounds. Build finance team. Ensure regulatory compliance.',
      benefits: 'Equity package. ESOP. Flexible work. International travel. High impact role.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.EXECUTIVE,
      workFormat: WorkFormat.HYBRID, country: 'Singapore', city: 'Singapore',
      salaryMin: 200000, salaryMax: 280000, salaryCurrency: 'SGD',
      category: 'finance', skillNames: [],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['cfo', 'fintech', 'startup'],
    },

    // ── Education (4) ────────────────────────────────────────────────────────
    {
      title: 'Online Course Developer',
      description: 'Kyiv EdTech platform seeks a Course Developer to design and produce engaging online learning programs in tech and business disciplines.',
      requirements: '2+ years instructional design. Experience with LMS platforms. Video production skills a plus. Strong writing skills.',
      responsibilities: 'Develop course curricula. Script and produce video lessons. Create assessments. Collaborate with subject matter experts.',
      benefits: 'Remote work. Access to all platform courses. Flexible schedule. Impact-driven culture.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.REMOTE, country: 'Ukraine', city: 'Kyiv',
      salaryMin: 40000, salaryMax: 60000, salaryCurrency: 'UAH',
      category: 'education', skillNames: [],
      employerIdx: 0, vacanciesCount: 2, requiredLanguages: ['Ukrainian', 'English'],
      tags: ['edtech', 'elearning', 'instructional-design'],
    },
    {
      title: 'English Teacher',
      description: 'Madrid international school is hiring a qualified English Teacher for secondary school students. Both native and non-native speakers welcome.',
      requirements: 'CELTA or TEFL certification. B2+ Spanish preferred. Experience with teenagers. Enthusiastic and patient.',
      responsibilities: 'Deliver English lessons to groups of 15-20 students. Prepare lesson plans. Assess student progress. Communicate with parents.',
      benefits: 'School provided housing support. Health insurance. Paid summer vacation. Cultural immersion.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.OFFICE, country: 'Spain', city: 'Madrid',
      salaryMin: 22000, salaryMax: 28000, salaryCurrency: 'EUR',
      category: 'education', skillNames: [],
      employerIdx: 1, vacanciesCount: 3, requiredLanguages: ['English', 'Spanish'],
      tags: ['teaching', 'english', 'school'],
    },
    {
      title: 'Corporate Trainer',
      description: 'Amsterdam consulting firm is looking for a Corporate Trainer specializing in leadership and team effectiveness for Fortune 500 clients.',
      requirements: '5+ years corporate training experience. Certification in coaching (ICF or equivalent). Excellent facilitation skills.',
      responsibilities: 'Design and deliver training programs. Conduct needs assessments. Measure training impact. Develop e-learning modules.',
      benefits: 'Hybrid work. 26 days vacation. Travel expenses covered. Annual coaching supervision.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'Netherlands', city: 'Amsterdam',
      salaryMin: 70000, salaryMax: 90000, salaryCurrency: 'EUR',
      category: 'education', skillNames: [],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'Dutch'],
      tags: ['training', 'leadership', 'corporate'],
    },
    {
      title: 'E-Learning Designer (Part-Time)',
      description: 'Vancouver-based university is looking for a part-time E-Learning Designer to modernize online course offerings for adult learners.',
      requirements: '2+ years e-learning design. Articulate Storyline or similar. Instructional design principles. Accessibility awareness.',
      responsibilities: 'Convert existing content to interactive e-learning. Create SCORM packages. Collaborate with faculty. Test and iterate.',
      benefits: 'Part-time 20h/week. Flexible scheduling. University benefits. Potential to go full-time.',
      jobType: JobType.PART_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.REMOTE, country: 'Canada', city: 'Vancouver',
      salaryMin: 35, salaryMax: 50, salaryCurrency: 'CAD',
      category: 'education', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['elearning', 'university', 'part-time'],
    },

    // ── Medicine (4) ─────────────────────────────────────────────────────────
    {
      title: 'Medical Data Analyst',
      description: 'Berlin university hospital is seeking a Medical Data Analyst to work on clinical data pipelines and support research studies.',
      requirements: '3+ years data analysis. Experience with medical or health data. SQL and Python proficiency. Knowledge of GDPR/HIPAA.',
      responsibilities: 'Analyse clinical datasets. Build dashboards for medical staff. Maintain data quality. Support research publications.',
      benefits: 'Public sector employment. 30 days leave. Pension. Flexible hybrid arrangements.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Germany', city: 'Berlin',
      salaryMin: 55000, salaryMax: 70000, salaryCurrency: 'EUR',
      category: 'medicine', skillNames: ['SQL', 'Python', 'Power BI'],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['German', 'English'],
      tags: ['health-data', 'clinical', 'analyst'],
    },
    {
      title: 'Hospital Pharmacist',
      description: 'Manchester NHS Trust is recruiting a Hospital Pharmacist to join our clinical pharmacy team in a busy general hospital.',
      requirements: 'MPharm degree and GPhC registration. Hospital pharmacy experience preferred. Clinical knowledge of drug interactions.',
      responsibilities: 'Dispense medications. Provide clinical pharmacy services. Advise clinical teams. Counsel patients.',
      benefits: 'NHS pension. 27 days annual leave + bank holidays. NHS discounts. Career development.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.OFFICE, country: 'United Kingdom', city: 'Manchester',
      salaryMin: 43000, salaryMax: 50000, salaryCurrency: 'GBP',
      category: 'medicine', skillNames: [],
      employerIdx: 2, vacanciesCount: 2, requiredLanguages: ['English'],
      tags: ['pharmacy', 'nhs', 'hospital'],
    },
    {
      title: 'Health IT Consultant',
      description: 'Melbourne consulting company is seeking a Health IT Consultant to lead digital health transformation projects for public hospitals.',
      requirements: '5+ years health IT experience. HL7 FHIR knowledge. Project management skills. Stakeholder management experience.',
      responsibilities: 'Lead implementation of clinical systems. Conduct workshops with clinical staff. Manage project delivery. Write requirements.',
      benefits: 'Remote work. Competitive consulting rates. Travel expenses. Flexible contract.',
      jobType: JobType.CONTRACT, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.REMOTE, country: 'Australia', city: 'Melbourne',
      salaryMin: 130000, salaryMax: 160000, salaryCurrency: 'AUD',
      category: 'medicine', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['health-it', 'digital-health', 'consultant'],
    },
    {
      title: 'Clinical Research Coordinator',
      description: 'Tel Aviv medical center seeks a Clinical Research Coordinator to manage Phase II–III oncology clinical trials from initiation to closeout.',
      requirements: '2+ years CRC experience. Knowledge of GCP/ICH guidelines. Attention to detail. Strong organizational skills.',
      responsibilities: 'Coordinate study activities. Recruit and screen participants. Collect and verify data. Liaise with sponsors and CROs.',
      benefits: 'Health insurance. 21 days leave. Professional training. Academic research environment.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.OFFICE, country: 'Israel', city: 'Tel Aviv',
      salaryMin: 18000, salaryMax: 25000, salaryCurrency: 'ILS',
      category: 'medicine', skillNames: [],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['Hebrew', 'English'],
      tags: ['clinical-research', 'oncology', 'trials'],
    },

    // ── Law (4) ──────────────────────────────────────────────────────────────
    {
      title: 'Corporate Lawyer',
      description: 'Geneva international law firm is seeking a Corporate Lawyer to advise on M&A transactions and corporate governance for multinational clients.',
      requirements: '5+ years corporate law experience. Swiss bar admission or foreign equivalent. M&A transaction experience. Fluent English and French.',
      responsibilities: 'Draft and negotiate transaction documents. Advise clients on corporate matters. Coordinate cross-border deals. Manage client relationships.',
      benefits: 'Prestigious firm. Competitive compensation. International environment. Partnership track.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'Switzerland', city: 'Geneva',
      salaryMin: 150000, salaryMax: 200000, salaryCurrency: 'CHF',
      category: 'law', skillNames: [],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'French'],
      tags: ['corporate-law', 'ma', 'international'],
    },
    {
      title: 'Legal Consultant (IT Law)',
      description: 'Warsaw tech company is hiring a Legal Consultant to handle contracts, GDPR compliance, and intellectual property matters.',
      requirements: '3+ years commercial legal experience. GDPR expertise. Contract drafting skills. English C1+.',
      responsibilities: 'Review and draft contracts. Advise on data protection. Manage IP portfolio. Support fundraising documentation.',
      benefits: 'Hybrid work. Private healthcare. Multisport card. Startup environment.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Poland', city: 'Warsaw',
      salaryMin: 15000, salaryMax: 20000, salaryCurrency: 'PLN',
      category: 'law', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['Polish', 'English'],
      tags: ['it-law', 'gdpr', 'contracts'],
    },
    {
      title: 'Compliance Officer',
      description: 'London fintech is seeking a Compliance Officer to ensure adherence to FCA regulations and develop the compliance framework for a growing payment platform.',
      requirements: '4+ years compliance experience in financial services. FCA regulatory knowledge. Risk assessment skills. CAMS or ICA qualification preferred.',
      responsibilities: 'Monitor regulatory changes. Develop compliance policies. Conduct training. Liaise with FCA.',
      benefits: 'Hybrid work. 25 days leave. Private healthcare. Performance bonus.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'United Kingdom', city: 'London',
      salaryMin: 75000, salaryMax: 95000, salaryCurrency: 'GBP',
      category: 'law', skillNames: [],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['compliance', 'fintech', 'fca'],
    },
    {
      title: 'Paralegal (International Trade)',
      description: 'Kyiv law firm specializing in international trade law is seeking a motivated Paralegal to support senior attorneys.',
      requirements: 'Law degree. English C1+. Interest in international trade and customs law. Strong research skills.',
      responsibilities: 'Conduct legal research. Draft correspondence. Organize case files. Support document preparation.',
      benefits: 'Excellent learning opportunity. Mentoring from senior lawyers. Hybrid work. Possibility of advancement.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.INTERN,
      workFormat: WorkFormat.HYBRID, country: 'Ukraine', city: 'Kyiv',
      salaryMin: 20000, salaryMax: 35000, salaryCurrency: 'UAH',
      category: 'law', skillNames: [],
      employerIdx: 2, vacanciesCount: 2, requiredLanguages: ['Ukrainian', 'English'],
      tags: ['paralegal', 'international-trade', 'junior'],
    },

    // ── Logistics (4) ────────────────────────────────────────────────────────
    {
      title: 'Supply Chain Manager',
      description: 'Hamburg logistics company is seeking an experienced Supply Chain Manager to optimize procurement and distribution for European FMCG clients.',
      requirements: '6+ years supply chain experience. ERP system expertise (SAP preferred). Lean/Six Sigma certification. Strong negotiation skills.',
      responsibilities: 'Manage supplier relationships. Optimize inventory levels. Lead supply chain projects. Oversee cross-docking operations.',
      benefits: 'Competitive salary. Car allowance. 30 days vacation. Pension plan.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.OFFICE, country: 'Germany', city: 'Hamburg',
      salaryMin: 80000, salaryMax: 100000, salaryCurrency: 'EUR',
      category: 'logistics', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['German', 'English'],
      tags: ['supply-chain', 'fmcg', 'logistics'],
    },
    {
      title: 'Logistics Coordinator',
      description: 'Gdansk freight company is looking for a Logistics Coordinator to manage shipments between Poland and Western Europe.',
      requirements: '2+ years logistics experience. Knowledge of customs procedures. Good German or English. Experience with TMS systems.',
      responsibilities: 'Book and track shipments. Coordinate with carriers. Resolve shipment issues. Maintain documentation.',
      benefits: 'Hybrid work. Private healthcare. Annual bonus. International work environment.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Poland', city: 'Gdansk',
      salaryMin: 7000, salaryMax: 10000, salaryCurrency: 'PLN',
      category: 'logistics', skillNames: [],
      employerIdx: 1, vacanciesCount: 2, requiredLanguages: ['Polish', 'English'],
      tags: ['freight', 'customs', 'coordinator'],
    },
    {
      title: 'Operations Manager',
      description: 'Dubai e-commerce fulfillment company seeks an Operations Manager to oversee warehouse and last-mile delivery for the UAE market.',
      requirements: '5+ years operations management. Warehouse management experience. KPI driven. Strong leadership skills.',
      responsibilities: 'Lead warehouse operations. Manage team of 50+ staff. Optimize workflows. Ensure delivery SLAs. Report to COO.',
      benefits: 'Tax-free salary. Annual flight ticket. Health insurance. Housing allowance.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.OFFICE, country: 'UAE', city: 'Dubai',
      salaryMin: 20000, salaryMax: 28000, salaryCurrency: 'AED',
      category: 'logistics', skillNames: [],
      employerIdx: 2, vacanciesCount: 1, requiredLanguages: ['English', 'Arabic'],
      tags: ['operations', 'warehouse', 'ecommerce'],
    },
    {
      title: 'Freight Forwarder',
      description: 'Rotterdam port-based logistics broker is hiring a Freight Forwarder to handle ocean and air freight for import/export clients.',
      requirements: '2+ years freight forwarding. Knowledge of Incoterms. Experience with ocean or air freight. Dutch or English fluency.',
      responsibilities: 'Arrange sea and air shipments. Prepare customs documentation. Negotiate with carriers. Track shipments and resolve delays.',
      benefits: 'Office near the port. 25 days leave. NS travel pass. Team events.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.OFFICE, country: 'Netherlands', city: 'Rotterdam',
      salaryMin: 45000, salaryMax: 58000, salaryCurrency: 'EUR',
      category: 'logistics', skillNames: [],
      employerIdx: 0, vacanciesCount: 2, requiredLanguages: ['English', 'Dutch'],
      tags: ['freight', 'ocean', 'import-export'],
    },

    // ── Sales (6) ────────────────────────────────────────────────────────────
    {
      title: 'B2B Sales Manager',
      description: 'Kyiv SaaS company is hiring a B2B Sales Manager to develop relationships with enterprise clients across Ukraine and the CEE region.',
      requirements: '3+ years B2B sales. CRM experience (Salesforce/HubSpot). Strong negotiation skills. Technical product aptitude.',
      responsibilities: 'Manage the full sales cycle. Conduct product demos. Negotiate and close contracts. Maintain client relationships.',
      benefits: 'Base + commission. Remote work possible. Medical insurance. Learning budget.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Ukraine', city: 'Kyiv',
      salaryMin: 50000, salaryMax: 100000, salaryCurrency: 'UAH',
      category: 'sales', skillNames: [],
      employerIdx: 1, vacanciesCount: 2, requiredLanguages: ['Ukrainian', 'English'],
      tags: ['b2b', 'saas', 'sales'],
    },
    {
      title: 'Business Development Representative',
      description: 'Austin tech startup is building their outbound sales team and seeking a BDR to prospect and qualify leads for Account Executives.',
      requirements: '1+ year outbound sales. Cold calling and email outreach experience. CRM proficiency. High energy and resilience.',
      responsibilities: 'Prospect and outreach to target accounts. Qualify leads via calls and emails. Book meetings for AEs. Meet pipeline quotas.',
      benefits: 'Base + OTE. Remote work. Health/dental/vision. Equity. Clear promotion path.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.REMOTE, country: 'USA', city: 'Austin',
      salaryMin: 50000, salaryMax: 70000, salaryCurrency: 'USD',
      category: 'sales', skillNames: [],
      employerIdx: 2, vacanciesCount: 3, requiredLanguages: ['English'],
      tags: ['bdr', 'sdr', 'outbound'],
    },
    {
      title: 'Account Executive (EMEA)',
      description: 'London enterprise software company is hiring an Account Executive to close new business across EMEA for their data management platform.',
      requirements: '5+ years enterprise SaaS sales. EMEA territory experience. Complex deal management. Track record of exceeding quota.',
      responsibilities: 'Run enterprise sales cycles. Build executive relationships. Lead contract negotiations. Forecast accurately.',
      benefits: 'Competitive base + uncapped commission. 25 days leave. Laptop + phone. ESPP.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'United Kingdom', city: 'London',
      salaryMin: 80000, salaryMax: 120000, salaryCurrency: 'GBP',
      category: 'sales', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['enterprise', 'saas', 'emea'],
    },
    {
      title: 'Regional Sales Director (DACH)',
      description: 'Munich cybersecurity company is looking for a Regional Sales Director to lead the DACH sales team and drive revenue growth.',
      requirements: '8+ years sales leadership. Experience managing teams of 5+. Cybersecurity market knowledge. German and English fluency.',
      responsibilities: 'Lead and coach a team of AEs. Own regional revenue target. Develop go-to-market strategy. Build executive relationships.',
      benefits: 'Leadership role. High OTE potential. Company car. ESOP. International conferences.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.LEAD,
      workFormat: WorkFormat.HYBRID, country: 'Germany', city: 'Munich',
      salaryMin: 140000, salaryMax: 180000, salaryCurrency: 'EUR',
      category: 'sales', skillNames: [],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['German', 'English'],
      tags: ['sales-leadership', 'dach', 'cybersecurity'],
    },
    {
      title: 'Inside Sales Specialist',
      description: 'Warsaw IT distribution company is growing its inside sales team to handle inbound and upsell opportunities for SME clients.',
      requirements: '1+ year sales experience. Good telephone manner. CRM knowledge. Polish and English communication skills.',
      responsibilities: 'Handle inbound leads. Upsell existing accounts. Quote and process orders. Maintain accurate CRM records.',
      benefits: 'Base + commission. Private healthcare. Multisport card. On-site parking.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.OFFICE, country: 'Poland', city: 'Warsaw',
      salaryMin: 6000, salaryMax: 10000, salaryCurrency: 'PLN',
      category: 'sales', skillNames: [],
      employerIdx: 2, vacanciesCount: 3, requiredLanguages: ['Polish', 'English'],
      tags: ['inside-sales', 'b2b', 'it'],
    },
    {
      title: 'Sales Development Representative (Internship)',
      description: 'Amsterdam scale-up offers a paid SDR internship for students interested in a career in tech sales and business development.',
      requirements: 'Currently enrolled in bachelor or master program. Excellent communication. Curious and coachable. English B2+.',
      responsibilities: 'Research target accounts. Send outreach emails. Support AEs with prospecting. Learn sales tools and methodology.',
      benefits: 'Paid internship. Central Amsterdam office. Mentorship. Real impact from day one.',
      jobType: JobType.INTERNSHIP, experienceLevel: ExperienceLevel.INTERN,
      workFormat: WorkFormat.HYBRID, country: 'Netherlands', city: 'Amsterdam',
      salaryMin: 600, salaryMax: 900, salaryCurrency: 'EUR',
      category: 'sales', skillNames: [],
      employerIdx: 0, vacanciesCount: 2, requiredLanguages: ['English'],
      tags: ['internship', 'sdr', 'tech-sales'],
    },

    // ── HR (4) ───────────────────────────────────────────────────────────────
    {
      title: 'HR Manager',
      description: 'Kyiv tech company is looking for an experienced HR Manager to build people processes and culture for a 150-person engineering-led organization.',
      requirements: '4+ years HR management. Experience in tech companies. Knowledge of Ukrainian labor law. Strong interpersonal skills.',
      responsibilities: 'Own the full employee lifecycle. Drive engagement initiatives. Manage HR team of 2. Partner with leadership.',
      benefits: 'Hybrid work. Competitive salary. Training budget. Wellbeing program.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.HYBRID, country: 'Ukraine', city: 'Kyiv',
      salaryMin: 70000, salaryMax: 100000, salaryCurrency: 'UAH',
      category: 'hr', skillNames: [],
      employerIdx: 1, vacanciesCount: 1, requiredLanguages: ['Ukrainian', 'English'],
      tags: ['hr', 'people-ops', 'tech'],
    },
    {
      title: 'Talent Acquisition Specialist',
      description: 'Warsaw staffing agency is hiring a Talent Acquisition Specialist to source and recruit candidates across IT and finance sectors.',
      requirements: '2+ years recruitment experience. Boolean search skills. Experience with LinkedIn Recruiter. Excellent communicator.',
      responsibilities: 'Source candidates across channels. Screen and interview applicants. Manage hiring pipelines. Advise hiring managers.',
      benefits: 'Hybrid work. Commission on placements. Training. Private healthcare.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.MIDDLE,
      workFormat: WorkFormat.HYBRID, country: 'Poland', city: 'Warsaw',
      salaryMin: 8000, salaryMax: 13000, salaryCurrency: 'PLN',
      category: 'hr', skillNames: [],
      employerIdx: 2, vacanciesCount: 2, requiredLanguages: ['Polish', 'English'],
      tags: ['recruitment', 'talent-acquisition', 'it'],
    },
    {
      title: 'People Operations Manager',
      description: 'Berlin remote-first startup is seeking a People Operations Manager to scale HR infrastructure and create an exceptional employee experience globally.',
      requirements: '5+ years people ops experience. Experience with distributed teams. Workday or BambooHR knowledge. Data-driven approach.',
      responsibilities: 'Own onboarding and offboarding. Manage HR systems. Lead engagement surveys. Partner with team leads.',
      benefits: 'Fully remote. Stock options. Home office budget. 30 days leave.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.SENIOR,
      workFormat: WorkFormat.REMOTE, country: 'Germany', city: 'Berlin',
      salaryMin: 70000, salaryMax: 90000, salaryCurrency: 'EUR',
      category: 'hr', skillNames: [],
      employerIdx: 0, vacanciesCount: 1, requiredLanguages: ['English'],
      tags: ['people-ops', 'remote', 'startup'],
    },
    {
      title: 'Junior Recruiter',
      description: 'London recruitment consultancy is hiring a Junior Recruiter to place candidates in the tech and digital sectors.',
      requirements: 'Degree or equivalent. Strong communication skills. Interest in tech industry. Organised and target-driven.',
      responsibilities: 'Screen CVs and conduct phone interviews. Post job adverts. Update candidate database. Support senior recruiters.',
      benefits: 'Commission structure. 25 days leave. Mentoring. Monthly team socials. Clear career path.',
      jobType: JobType.FULL_TIME, experienceLevel: ExperienceLevel.JUNIOR,
      workFormat: WorkFormat.HYBRID, country: 'United Kingdom', city: 'London',
      salaryMin: 28000, salaryMax: 35000, salaryCurrency: 'GBP',
      category: 'hr', skillNames: [],
      employerIdx: 1, vacanciesCount: 2, requiredLanguages: ['English'],
      tags: ['recruiter', 'tech-recruitment', 'junior'],
    },
  ];

  const deadline = new Date();
  deadline.setMonth(deadline.getMonth() + 3);

  for (const def of JOBS) {
    const job = jobRepo.create({
      title: def.title,
      description: def.description,
      requirements: def.requirements,
      responsibilities: def.responsibilities,
      benefits: def.benefits,
      jobType: def.jobType,
      status: JobStatus.ACTIVE,
      experienceLevel: def.experienceLevel,
      workFormat: def.workFormat,
      country: def.country,
      city: def.city,
      salaryMin: def.salaryMin,
      salaryMax: def.salaryMax,
      salaryCurrency: def.salaryCurrency,
      isSalaryNegotiable: def.isSalaryNegotiable ?? false,
      category: def.category,
      requiredSkills: skills(...def.skillNames),
      employer: emp(def.employerIdx),
      employerId: emp(def.employerIdx).id,
      vacanciesCount: def.vacanciesCount ?? 1,
      requiredLanguages: def.requiredLanguages,
      tags: def.tags,
      isRemote: def.workFormat === WorkFormat.REMOTE,
      publishedAt: new Date(),
      applicationDeadline: deadline,
    });

    await jobRepo.save(job);
  }

  console.log(`✅ Inserted ${JOBS.length} jobs`);

  await DB.query(`
    UPDATE jobs
    SET "createdAt" = NOW() - (random() * INTERVAL '365 days')
  `);
  console.log('📅 Spread createdAt across the last year');

  await DB.destroy();
  console.log('✅ Done');
}

main().catch(err => { console.error(err); process.exit(1); });
